// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: dictionary.sql

package db

import (
	"context"
)

const addCategory = `-- name: AddCategory :one
INSERT INTO words_categories ("categoryName", "user_id")
VALUES ($1, $2::text)
RETURNING id, "categoryName", user_id
`

type AddCategoryParams struct {
	CategoryName string
	UserID       string
}

func (q *Queries) AddCategory(ctx context.Context, arg AddCategoryParams) (WordsCategory, error) {
	row := q.db.QueryRow(ctx, addCategory, arg.CategoryName, arg.UserID)
	var i WordsCategory
	err := row.Scan(&i.ID, &i.CategoryName, &i.UserID)
	return i, err
}

const addCategoryWithId = `-- name: AddCategoryWithId :exec
INSERT INTO words_categories ("id", "categoryName", "user_id")
VALUES ($1, $2, $3::text)
`

type AddCategoryWithIdParams struct {
	ID           int32
	CategoryName string
	UserID       string
}

func (q *Queries) AddCategoryWithId(ctx context.Context, arg AddCategoryWithIdParams) error {
	_, err := q.db.Exec(ctx, addCategoryWithId, arg.ID, arg.CategoryName, arg.UserID)
	return err
}

const addWord = `-- name: AddWord :exec
INSERT INTO words ("categoryId", "en", "pl", "user_id")
VALUES ($1, $2, $3, $4::text)
`

type AddWordParams struct {
	CategoryID int32
	En         string
	Pl         string
	UserID     string
}

func (q *Queries) AddWord(ctx context.Context, arg AddWordParams) error {
	_, err := q.db.Exec(ctx, addWord,
		arg.CategoryID,
		arg.En,
		arg.Pl,
		arg.UserID,
	)
	return err
}

const deleteCategory = `-- name: DeleteCategory :exec
DELETE
FROM words_categories
WHERE words_categories.id = $1
`

func (q *Queries) DeleteCategory(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteCategory, id)
	return err
}

const getAllCategories = `-- name: GetAllCategories :many
SELECT words_categories.id, words_categories."categoryName", words_categories."user_id"
FROM words_categories
`

func (q *Queries) GetAllCategories(ctx context.Context) ([]WordsCategory, error) {
	rows, err := q.db.Query(ctx, getAllCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WordsCategory
	for rows.Next() {
		var i WordsCategory
		if err := rows.Scan(&i.ID, &i.CategoryName, &i.UserID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllWords = `-- name: GetAllWords :many
SELECT words.id,
       words.pl,
       words.en,
       words.user_defined::bool as user_defined,
       words_categories.id, words_categories."categoryName", words_categories.user_id,
       COUNT(*) over ()         as total_rows
FROM words
         JOIN words_categories ON words."categoryId" = words_categories.id
WHERE words.en LIKE '%' || $1::text || '%'
   OR words.pl LIKE '%' || $1::text || '%'
ORDER BY CASE
             WHEN $2 = 'pl' AND $3::bool = true THEN pl
             WHEN $2 = 'en' AND $3::bool = true THEN en
             END DESC,
         CASE
             WHEN $2 = 'pl' AND $3::bool = false THEN pl
             WHEN $2 = 'en' AND $3::bool = false THEN en
             END
LIMIT $5 OFFSET $4
`

type GetAllWordsParams struct {
	Search         string
	SortColumn     interface{}
	SortDescending bool
	PageOffset     int32
	PageSize       int32
}

type GetAllWordsRow struct {
	ID            int32
	Pl            string
	En            string
	UserDefined   bool
	WordsCategory WordsCategory
	TotalRows     int64
}

func (q *Queries) GetAllWords(ctx context.Context, arg GetAllWordsParams) ([]GetAllWordsRow, error) {
	rows, err := q.db.Query(ctx, getAllWords,
		arg.Search,
		arg.SortColumn,
		arg.SortDescending,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllWordsRow
	for rows.Next() {
		var i GetAllWordsRow
		if err := rows.Scan(
			&i.ID,
			&i.Pl,
			&i.En,
			&i.UserDefined,
			&i.WordsCategory.ID,
			&i.WordsCategory.CategoryName,
			&i.WordsCategory.UserID,
			&i.TotalRows,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCategoryById = `-- name: GetCategoryById :one
SELECT words_categories.id, words_categories."categoryName", words_categories."user_id"
FROM words_categories
WHERE words_categories.id = $1
`

func (q *Queries) GetCategoryById(ctx context.Context, id int32) (WordsCategory, error) {
	row := q.db.QueryRow(ctx, getCategoryById, id)
	var i WordsCategory
	err := row.Scan(&i.ID, &i.CategoryName, &i.UserID)
	return i, err
}

const getCategoryByName = `-- name: GetCategoryByName :one
SELECT words_categories.id, words_categories."categoryName", words_categories."user_id"
FROM words_categories
WHERE words_categories."categoryName" = $1
`

func (q *Queries) GetCategoryByName(ctx context.Context, categoryName string) (WordsCategory, error) {
	row := q.db.QueryRow(ctx, getCategoryByName, categoryName)
	var i WordsCategory
	err := row.Scan(&i.ID, &i.CategoryName, &i.UserID)
	return i, err
}

const getWordsByCategory = `-- name: GetWordsByCategory :many
SELECT id, "categoryId", en, pl, user_defined, user_id
FROM words
WHERE words."categoryId" = $1
`

func (q *Queries) GetWordsByCategory(ctx context.Context, categoryID int32) ([]Word, error) {
	rows, err := q.db.Query(ctx, getWordsByCategory, categoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Word
	for rows.Next() {
		var i Word
		if err := rows.Scan(
			&i.ID,
			&i.CategoryId,
			&i.En,
			&i.Pl,
			&i.UserDefined,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
