// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: dictionary.sql

package db

import (
	"context"
)

const addCategory = `-- name: AddCategory :one
INSERT INTO words_categories ("categoryName")
VALUES ($1)
RETURNING id, "categoryName"
`

func (q *Queries) AddCategory(ctx context.Context, categoryName string) (WordsCategory, error) {
	row := q.db.QueryRow(ctx, addCategory, categoryName)
	var i WordsCategory
	err := row.Scan(&i.ID, &i.CategoryName)
	return i, err
}

const addCategoryWithId = `-- name: AddCategoryWithId :exec
INSERT INTO words_categories ("id", "categoryName")
VALUES ($1, $2)
`

type AddCategoryWithIdParams struct {
	ID           int32
	CategoryName string
}

func (q *Queries) AddCategoryWithId(ctx context.Context, arg AddCategoryWithIdParams) error {
	_, err := q.db.Exec(ctx, addCategoryWithId, arg.ID, arg.CategoryName)
	return err
}

const addWord = `-- name: AddWord :exec
INSERT INTO words ("categoryId", "en", "pl")
VALUES ($1, $2, $3)
`

type AddWordParams struct {
	CategoryID int32
	En         string
	Pl         string
}

func (q *Queries) AddWord(ctx context.Context, arg AddWordParams) error {
	_, err := q.db.Exec(ctx, addWord, arg.CategoryID, arg.En, arg.Pl)
	return err
}

const getAllCategories = `-- name: GetAllCategories :many
SELECT words_categories.id, words_categories."categoryName"
FROM words_categories
`

func (q *Queries) GetAllCategories(ctx context.Context) ([]WordsCategory, error) {
	rows, err := q.db.Query(ctx, getAllCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WordsCategory
	for rows.Next() {
		var i WordsCategory
		if err := rows.Scan(&i.ID, &i.CategoryName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllWords = `-- name: GetAllWords :many
SELECT words.id,
       words.pl,
       words.en,
       words.user_defined::bool as user_defined,
       words_categories.id, words_categories."categoryName",
       COUNT(*) over ()         as total_rows
FROM words
         JOIN words_categories ON words."categoryId" = words_categories.id
WHERE words.en LIKE '%' || $1::text || '%'
   OR words.pl LIKE '%' || $1::text || '%'
ORDER BY CASE
             WHEN $2 = 'pl' AND $3::bool = true THEN pl
             WHEN $2 = 'en' AND $3::bool = true THEN en
             END DESC,
         CASE
             WHEN $2 = 'pl' AND $3::bool = false THEN pl
             WHEN $2 = 'en' AND $3::bool = false THEN en
             END
LIMIT $5 OFFSET $4
`

type GetAllWordsParams struct {
	Search         string
	SortColumn     interface{}
	SortDescending bool
	PageOffset     int32
	PageSize       int32
}

type GetAllWordsRow struct {
	ID            int32
	Pl            string
	En            string
	UserDefined   bool
	WordsCategory WordsCategory
	TotalRows     int64
}

func (q *Queries) GetAllWords(ctx context.Context, arg GetAllWordsParams) ([]GetAllWordsRow, error) {
	rows, err := q.db.Query(ctx, getAllWords,
		arg.Search,
		arg.SortColumn,
		arg.SortDescending,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllWordsRow
	for rows.Next() {
		var i GetAllWordsRow
		if err := rows.Scan(
			&i.ID,
			&i.Pl,
			&i.En,
			&i.UserDefined,
			&i.WordsCategory.ID,
			&i.WordsCategory.CategoryName,
			&i.TotalRows,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCategoryByName = `-- name: GetCategoryByName :one
SELECT words_categories.id, words_categories."categoryName"
FROM words_categories
WHERE words_categories."categoryName" = $1
`

func (q *Queries) GetCategoryByName(ctx context.Context, categoryName string) (WordsCategory, error) {
	row := q.db.QueryRow(ctx, getCategoryByName, categoryName)
	var i WordsCategory
	err := row.Scan(&i.ID, &i.CategoryName)
	return i, err
}
