// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Flashcard struct {
	ID        int32
	Name      string
	Author    string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type Word struct {
	ID        int32
	En        string
	Pl        string
	Author    string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type WordsFlashcard struct {
	WordID      int32
	FlashcardID int32
	CreatedAt   pgtype.Timestamptz
}
