// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

type Word struct {
	ID         int32
	CategoryId int32
	En         string
	Pl         string
}

type WordsCategory struct {
	ID           int32
	CategoryName string
}
