// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Word struct {
	ID          int32
	CategoryId  int32
	En          string
	Pl          string
	UserDefined pgtype.Bool
	UserID      pgtype.Text
}

type WordsCategory struct {
	ID           int32
	CategoryName string
	UserID       pgtype.Text
}
