// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: quiz.sql

package db

import (
	"context"
)

const getQuizQuestions = `-- name: GetQuizQuestions :many
SELECT id, "categoryId", en, pl, user_defined
FROM words
ORDER BY RANDOM()
LIMIT $1
`

func (q *Queries) GetQuizQuestions(ctx context.Context, limit int32) ([]Word, error) {
	rows, err := q.db.Query(ctx, getQuizQuestions, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Word
	for rows.Next() {
		var i Word
		if err := rows.Scan(
			&i.ID,
			&i.CategoryId,
			&i.En,
			&i.Pl,
			&i.UserDefined,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
