name: "Build and Push hello-word API docker image"

permissions:
  packages: write
  contents: read

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - "api/**/*"

jobs:
  build-and-push:
    runs-on: ubuntu-22.04
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log into docker registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{vars.CONTAINER_REGISTRY_USER}}
          password: ${{secrets.CONTAINER_REGISTRY_PASSWORD}}

      - name: Build docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          context: "api"
          tags: |
            ghcr.io/pawelataman/hello-word-api:latest
            ghcr.io/pawelataman/hello-word-api:${{github.sha}}