name: "Build and Push API docker image"

on:
  push:
    branches:
      - dev
    paths:
      - "api/**/*"

permissions:
  packages: write
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log into docker registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.CONTAINER_REGISTRY_PASSWORD}}

      - name: Build docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          context: "{{defaultContext}}:api"
          tags: |
            ghcr.io/pawelataman/hello-word-api@latest
            ghcr.io/pawelataman/hello-word-api@${{github.sha}}
